services:
  - name: dbmongo
    env: docker
    dockerfilePath: ./mongoDb/Dockerfile
    containerPorts:
      - 27017
    volumes:
      - mongodb-data:/data/db

  - name: mongodb_code
    env: docker
    dockerfilePath: ./mongoCode/Dockerfile
    containerPorts:
      - 27000
    dependsOn:
      - dbmongo

  - name: backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    containerPorts:
      - 8000
    dependsOn:
      - dbmongo
      - mongodb_code

  - name: frontend
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    containerPorts:
      - 3000
    dependsOn:
      - dbmongo
      - mongodb_code
      - backend

volumes:
  - name: mongodb-data

networks:
  - name: money-tracker-network
