services:
  - type: mongodb
    name: dbmongo
    dockerfilePath: ./mongoDb/Dockerfile
    env:
      - key: MONGO_INITDB_ROOT_USERNAME
        value: root
      - key: MONGO_INITDB_ROOT_PASSWORD
        value: root
    ports:
      - 8003:27017
    
  - type: web
    name: mongodb_code
    dockerfilePath: ./mongoCode/Dockerfile
    envFrom: 
      - service:dbmongo
        type: secret
    ports:
      - 27000:27000
    
  - type: web  
    name: backend
    dockerfilePath: ./backend/Dockerfile
    envFrom:
      - service:dbmongo
        type: secret  
    ports:
      - 8000:8000
    
  - type: web
    name: frontend 
    dockerfilePath: ./frontend/Dockerfile
    envFrom:
      - service:dbmongo
        type: secret
    ports:
      - 3000:3000
