services:
  - name: dbmongo
    type: web
    env: docker
    repo: https://github.com/your-repo/your-project
    dockerContext: ./mongoDb
    dockerfilePath: Dockerfile
    envVars:
      - key: MONGO_INITDB_ROOT_USERNAME
        value: root  
      - key: MONGO_INITDB_ROOT_PASSWORD
        value: root
    

  - name: mongodb_code 
    type: worker
    env: docker
    repo: https://github.com/your-repo/your-project  
    dockerContext: ./mongoCode
    dockerfilePath: Dockerfile
  
    envVars:
      - key: MONGO_CONNECTION_STRING
        fromService:
          name: dbmongo
          property: connectionString

  - name: backend
    type: web  
    buildCommand: npm install
    startCommand: npm start
    repo: https://github.com/your-repo/your-project
    dockerContext: ./backend
    dockerfilePath: Dockerfile

    envVars:
      - key: MONGO_CONNECTION_STRING  
        fromService:
          name: dbmongo
          property: connectionString

  - name: frontend  
    type: web
    buildCommand: npm install  
    startCommand: npm start
    repo: https://github.com/your-repo/your-project
    dockerContext: ./frontend  
    dockerfilePath: Dockerfile

    envVars:
      - key: API_URL
        fromService:
          name: backend
          property: hostport

databases: []
